#!/bin/bash
set -e

CDIR=$(cd `dirname "$0"`/.. && pwd)
cd "$CDIR"

ORG_PATH="github.com/cloudflare"
REPO_PATH="${ORG_PATH}/cfssl"

IMAGE="cfssl"
IMAGE_PREFIX=${IMAGE_PREFIX:=cfssl}

IMAGE_TAG=$(git describe --abbrev=0 --tags)

dockerfile () {
    cat <<"EOF"
FROM

COPY cfssl* /usr/bin/

VOLUME [ "/etc/cfssl" ]
WORKDIR /etc/cfssl

EXPOSE 8888

ENTRYPOINT ["cfssl"]
CMD ["--help"]
EOF
}

relabel() {
  chcon -R -t "${1}" "${CDIR}"
}

OS_PLATFORM_ARG=(-os="linux")
OS_ARCH_ARG=(-arch="amd64 arm arm64")

# Temporarily change SELinux context of build directory
if [[ "$(command getenforce 2>&1)" == "Enforcing" ]]; then
  USER_CONTEXT="$(getfattr --only-values -n security.selinux "${CDIR}" | awk -F':' '{ print $3 }')"
  CONTAINER_CONTEXT="svirt_sandbox_file_t"

  trap "relabel '${USER_CONTEXT}'" EXIT
  relabel "${CONTAINER_CONTEXT}"
fi

# Get rid of existing binaries
rm -f *-386
rm -f *-amd64
rm -f dist/*
docker run --rm -v "${CDIR}":/go/src/${REPO_PATH} -u $(id -u):$(id -g) cfssl-build "${OS_PLATFORM_ARG[@]}" "${OS_ARCH_ARG[@]}" -output="dist/{{.Dir}}_{{.OS}}-{{.Arch}}" -ldflags='-w -extldflags "-static"' ./cmd/...

docker run --rm --privileged multiarch/qemu-user-static:register --reset
for arch in arm arm64 amd64; do
    DOCKER_BUILD_DIR=$(mktemp -d)
    
    image_arch=""
    if [ "$arch" == "arm" ]; then
        image_arch="armhf"
    else
        image_arch="$arch"
    fi

    printf "%s" "$(dockerfile)" | sed -e "s;^FROM;FROM multiarch/alpine:${image_arch}-v3.6;" -e "s/{{ARCH}}/${arch}/g" > $DOCKER_BUILD_DIR/Dockerfile
    cp dist/cfssl*_linux-${arch} $DOCKER_BUILD_DIR/
    for f in $DOCKER_BUILD_DIR/cfssl*; do mv "$f" "`echo $f | sed s/_linux-${arch}//`"; done
    docker build --no-cache --rm -t $IMAGE_PREFIX/$IMAGE-$arch:$IMAGE_TAG $DOCKER_BUILD_DIR
    docker push $IMAGE_PREFIX/$IMAGE-$arch:$IMAGE_TAG
done
cat $CDIR/script/manifest.yml | sed -e "s/IMAGE_PREFIX/$IMAGE_PREFIX/g" -e "s/IMAGE_NAME/$IMAGE/g" -e "s/IMAGE_TAG/$IMAGE_TAG/g" > dist/manifest.yml
manifest-tool --username $DOCKER_USER --password $DOCKER_PASS push from-spec dist/manifest.yml
